package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.types.SiteSpaceType;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "CustomPages")
public class CustomPages implements java.io.Serializable {

	private int id;
	private String pageName;
	private String title;
	private String description;
	private SiteSpaceType siteSpaceType;
	private Date inserted;

	public CustomPages() {
	}

	public CustomPages(int id, String pageName, String title, String description, SiteSpaceType siteSpaceType, Date inserted) {
		super();
		this.id = id;
		this.pageName = pageName;
		this.title = title;
		this.description = description;
		this.inserted = inserted;
		this.siteSpaceType = siteSpaceType;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "pageName", nullable = false, length = 50)
	public String getPageName() {
		return pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	@Column(name = "description", nullable = false, length = 8000)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "siteSpaceType", nullable = false, length = 20)
	public SiteSpaceType getSiteSpaceType() {
		return siteSpaceType;
	}

	public void setSiteSpaceType(SiteSpaceType siteSpaceType) {
		this.siteSpaceType = siteSpaceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inserted", nullable = false, length = 23)
	public Date getInserted() {
		return inserted;
	}

	public void setInserted(Date inserted) {
		this.inserted = inserted;
	}

}
