package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductTagsId generated by hbm2java
 */
@Embeddable
public class ProductTagsId implements java.io.Serializable {

	private int productId;
	private int tagId;

	public ProductTagsId() {
	}

	public ProductTagsId(int productId, int tagId) {
		this.productId = productId;
		this.tagId = tagId;
	}

	@Column(name = "productId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "tagId", nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductTagsId))
			return false;
		ProductTagsId castOther = (ProductTagsId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getTagId() == castOther.getTagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getTagId();
		return result;
	}

}
