package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product")
public class Product implements java.io.Serializable {

	private int id;
	private Category category;
	private Date created;
	private String title;
	private String subTitle;
	private String description;
	private String photoUrl;
	private BigDecimal price;
	private Set<ProductTags> productTagses = new HashSet<ProductTags>(0);

	public Product() {
	}

	public Product(int id, Category category, Date created, String title, String subTitle, String description, String photoUrl,
			BigDecimal price, String display) {
		this.id = id;
		this.category = category;
		this.created = created;
		this.title = title;
		this.subTitle = subTitle;
		this.description = description;
		this.photoUrl = photoUrl;
		this.price = price;
	}

	public Product(int id, Category category, Date created, String title, String subTitle, String description, String photoUrl,
			BigDecimal price, String display, Set<ProductTags> productTagses) {
		this.id = id;
		this.category = category;
		this.created = created;
		this.title = title;
		this.subTitle = subTitle;
		this.description = description;
		this.photoUrl = photoUrl;
		this.price = price;
		this.productTagses = productTagses;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryID", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 23)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "subTitle", nullable = false, length = 64)
	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	@Column(name = "description", nullable = false, length = 4096)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "photoURL", nullable = false)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Column(name = "price", nullable = false, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductTags> getProductTagses() {
		return this.productTagses;
	}

	public void setProductTagses(Set<ProductTags> productTagses) {
		this.productTagses = productTagses;
	}

}
