package com.entity.db;

// Generated 10 Nov 2013 6:11:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductTags generated by hbm2java
 */
@Entity
@Table(name = "ProductTags")
public class ProductTags implements java.io.Serializable {

	private ProductTagsId id;
	private Tag tag;
	private Product product;
	private Date created;

	public ProductTags() {
	}

	public ProductTags(ProductTagsId id, Tag tag, Product product, Date created) {
		this.id = id;
		this.tag = tag;
		this.product = product;
		this.created = created;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)),
			@AttributeOverride(name = "tagId", column = @Column(name = "tagId", nullable = false)) })
	public ProductTagsId getId() {
		return this.id;
	}

	public void setId(ProductTagsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tagId", nullable = false, insertable = false, updatable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 23)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
