package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.types.PublishingSectionType;

/**
 * Publishing generated by hbm2java
 */
@Entity
@Table(name = "Publishing")
public class Publishing implements java.io.Serializable {

	private int id;
	private Date created;
	private String title;
	private String subtitle;
	private String description;
	private Date eventDate;
	private PublishingSectionType section;
	private int readCount;

	public Publishing() {
	}

	public Publishing(int id, Date created, String title, String subtitle, String description, Date eventDate, PublishingSectionType section, int readCount) {
		this.id = id;
		this.created = created;
		this.title = title;
		this.subtitle = subtitle;
		this.description = description;
		this.eventDate = eventDate;
		this.section = section;
		this.readCount = readCount;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 23)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "subtitle", nullable = false, length = 64)
	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	@Column(name = "description", nullable = false, length = 2048)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventDate", nullable = false, length = 23)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "section", nullable = false, length = 50)
	public PublishingSectionType getSection() {
		return this.section;
	}

	public void setSection(PublishingSectionType section) {
		this.section = section;
	}

	@Column(name = "read_count", nullable = false)
	public int getReadCount() {
		return this.readCount;
	}

	public void setReadCount(int readCount) {
		this.readCount = readCount;
	}

}
