package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statistics generated by hbm2java
 */
@Entity
@Table(name = "Statistics", schema = "dbo", catalog = "WildPeacock")
public class Statistics implements java.io.Serializable {

	private int id;
	private String name;
	private int count;

	public Statistics() {
	}

	public Statistics(int id, String name, int count) {
		this.id = id;
		this.name = name;
		this.count = count;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
