package com.entity.db;

// Generated 08 Oct 2013 7:47:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemAudit generated by hbm2java
 */
@Entity
@Table(name = "SystemAudit", schema = "dbo", catalog = "WildPeacock")
public class SystemAudit implements java.io.Serializable {

	private int id;
	private int authorityId;
	private Date inserted;
	private String action;
	private String description;

	public SystemAudit() {
	}

	public SystemAudit(int id, int authorityId, Date inserted, String action, String description) {
		this.id = id;
		this.authorityId = authorityId;
		this.inserted = inserted;
		this.action = action;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "authorityId", nullable = false)
	public int getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(int authorityId) {
		this.authorityId = authorityId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inserted", nullable = false, length = 23)
	public Date getInserted() {
		return this.inserted;
	}

	public void setInserted(Date inserted) {
		this.inserted = inserted;
	}

	@Column(name = "action", nullable = false, length = 50)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "description", nullable = false, length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
